/* Generated by makeenums.pl */

#include "gdk.h"

GType
gdk_cursor_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
   /*   static const GEnumValue values[] = {
        { GDK_X_CURSOR, "", "x-cursor" },
        { GDK_ARROW, "", "arrow" },
        { GDK_BASED_ARROW_DOWN, "", "based-arrow-down" },
        { GDK_BASED_ARROW_UP, "", "based-arrow-up" },
        { GDK_BOAT, "", "boat" },
        { GDK_BOGOSITY, "", "bogosity" },
        { GDK_BOTTOM_LEFT_CORNER, "", "bottom-left-corner" },
        { GDK_BOTTOM_RIGHT_CORNER, "", "bottom-right-corner" },
        { GDK_BOTTOM_SIDE, "", "bottom-side" },
        { GDK_BOTTOM_TEE, "", "bottom-tee" },
        { GDK_BOX_SPIRAL, "", "box-spiral" },
        { GDK_CENTER_PTR, "", "center-ptr" },
        { GDK_CIRCLE, "", "circle" },
        { GDK_CLOCK, "", "clock" },
        { GDK_COFFEE_MUG, "", "coffee-mug" },
        { GDK_CROSS, "", "cross" },
        { GDK_CROSS_REVERSE, "", "cross-reverse" },
        { GDK_CROSSHAIR, "", "crosshair" },
        { GDK_DIAMOND_CROSS, "", "diamond-cross" },
        { GDK_DOT, "", "dot" },
        { GDK_DOTBOX, "", "dotbox" },
        { GDK_DOUBLE_ARROW, "", "double-arrow" },
        { GDK_DRAFT_LARGE, "", "draft-large" },
        { GDK_DRAFT_SMALL, "", "draft-small" },
        { GDK_DRAPED_BOX, "", "draped-box" },
        { GDK_EXCHANGE, "", "exchange" },
        { GDK_FLEUR, "", "fleur" },
        { GDK_GOBBLER, "", "gobbler" },
        { GDK_GUMBY, "", "gumby" },
        { GDK_HAND1, "", "hand1" },
        { GDK_HAND2, "", "hand2" },
        { GDK_HEART, "", "heart" },
        { GDK_ICON, "", "icon" },
        { GDK_IRON_CROSS, "", "iron-cross" },
        { GDK_LEFT_PTR, "", "left-ptr" },
        { GDK_LEFT_SIDE, "", "left-side" },
        { GDK_LEFT_TEE, "", "left-tee" },
        { GDK_LEFTBUTTON, "", "leftbutton" },
        { GDK_LL_ANGLE, "", "ll-angle" },
        { GDK_LR_ANGLE, "", "lr-angle" },
        { GDK_MAN, "", "man" },
        { GDK_MIDDLEBUTTON, "", "middlebutton" },
        { GDK_MOUSE, "", "mouse" },
        { GDK_PENCIL, "", "pencil" },
        { GDK_PIRATE, "", "pirate" },
        { GDK_PLUS, "", "plus" },
        { GDK_QUESTION_ARROW, "", "question-arrow" },
        { GDK_RIGHT_PTR, "", "right-ptr" },
        { GDK_RIGHT_SIDE, "", "right-side" },
        { GDK_RIGHT_TEE, "", "right-tee" },
        { GDK_RIGHTBUTTON, "", "rightbutton" },
        { GDK_RTL_LOGO, "", "rtl-logo" },
        { GDK_SAILBOAT, "", "sailboat" },
        { GDK_SB_DOWN_ARROW, "", "sb-down-arrow" },
        { GDK_SB_H_DOUBLE_ARROW, "", "sb-h-double-arrow" },
        { GDK_SB_LEFT_ARROW, "", "sb-left-arrow" },
        { GDK_SB_RIGHT_ARROW, "", "sb-right-arrow" },
        { GDK_SB_UP_ARROW, "", "sb-up-arrow" },
        { GDK_SB_V_DOUBLE_ARROW, "", "sb-v-double-arrow" },
        { GDK_SHUTTLE, "", "shuttle" },
        { GDK_SIZING, "", "sizing" },
        { GDK_SPIDER, "", "spider" },
        { GDK_SPRAYCAN, "", "spraycan" },
        { GDK_STAR, "", "star" },
        { GDK_TARGET, "", "target" },
        { GDK_TCROSS, "", "tcross" },
        { GDK_TOP_LEFT_ARROW, "", "top-left-arrow" },
        { GDK_TOP_LEFT_CORNER, "", "top-left-corner" },
        { GDK_TOP_RIGHT_CORNER, "", "top-right-corner" },
        { GDK_TOP_SIDE, "", "top-side" },
        { GDK_TOP_TEE, "", "top-tee" },
        { GDK_TREK, "", "trek" },
        { GDK_UL_ANGLE, "", "ul-angle" },
        { GDK_UMBRELLA, "", "umbrella" },
        { GDK_UR_ANGLE, "", "ur-angle" },
        { GDK_WATCH, "", "watch" },
        { GDK_XTERM, "", "xterm" },
        { GDK_LAST_CURSOR, "", "last-cursor" },
        { GDK_CURSOR_IS_PIXMAP, "", "cursor-is-pixmap" },
        { 0, NULL, NULL }
      };*/
      etype = g_enum_register_static ("GdkCursorType", NULL);//values);
    }
  return etype;
}


GType
gdk_drag_action_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_ACTION_DEFAULT, "", "default" },
        { GDK_ACTION_COPY, "", "copy" },
        { GDK_ACTION_MOVE, "", "move" },
        { GDK_ACTION_LINK, "", "link" },
        { GDK_ACTION_PRIVATE, "", "private" },
        { GDK_ACTION_ASK, "", "ask" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkDragAction", values);
    }
  return etype;
}


GType
gdk_drag_protocol_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_DRAG_PROTO_MOTIF, "", "motif" },
        { GDK_DRAG_PROTO_XDND, "", "xdnd" },
        { GDK_DRAG_PROTO_ROOTWIN, "", "rootwin" },
        { GDK_DRAG_PROTO_NONE, "", "none" },
        { GDK_DRAG_PROTO_WIN32_DROPFILES, "", "win32-dropfiles" },
        { GDK_DRAG_PROTO_OLE2, "", "ole2" },
        { GDK_DRAG_PROTO_LOCAL, "", "local" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkDragProtocol", values);
    }
  return etype;
}


GType
gdk_filter_return_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_FILTER_CONTINUE, "", "continue" },
        { GDK_FILTER_TRANSLATE, "", "translate" },
        { GDK_FILTER_REMOVE, "", "remove" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkFilterReturn", values);
    }
  return etype;
}


GType
gdk_event_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
     /* static const GEnumValue values[] = {
        { GDK_NOTHING, "", "nothing" },
        { GDK_DELETE, "", "delete" },
        { GDK_DESTROY, "", "destroy" },
        { GDK_EXPOSE, "", "expose" },
        { GDK_MOTION_NOTIFY, "", "motion-notify" },
        { GDK_BUTTON_PRESS, "", "button-press" },
        { GDK_2BUTTON_PRESS, "", "2button-press" },
        { GDK_3BUTTON_PRESS, "", "3button-press" },
        { GDK_BUTTON_RELEASE, "", "button-release" },
        { GDK_KEY_PRESS, "", "key-press" },
        { GDK_KEY_RELEASE, "", "key-release" },
        { GDK_ENTER_NOTIFY, "", "enter-notify" },
        { GDK_LEAVE_NOTIFY, "", "leave-notify" },
        { GDK_FOCUS_CHANGE, "", "focus-change" },
        { GDK_CONFIGURE, "", "configure" },
        { GDK_MAP, "", "map" },
        { GDK_UNMAP, "", "unmap" },
        { GDK_PROPERTY_NOTIFY, "", "property-notify" },
        { GDK_SELECTION_CLEAR, "", "selection-clear" },
        { GDK_SELECTION_REQUEST, "", "selection-request" },
        { GDK_SELECTION_NOTIFY, "", "selection-notify" },
        { GDK_PROXIMITY_IN, "", "proximity-in" },
        { GDK_PROXIMITY_OUT, "", "proximity-out" },
        { GDK_DRAG_ENTER, "", "drag-enter" },
        { GDK_DRAG_LEAVE, "", "drag-leave" },
        { GDK_DRAG_MOTION, "", "drag-motion" },
        { GDK_DRAG_STATUS, "", "drag-status" },
        { GDK_DROP_START, "", "drop-start" },
        { GDK_DROP_FINISHED, "", "drop-finished" },
        { GDK_CLIENT_EVENT, "", "client-event" },
        { GDK_VISIBILITY_NOTIFY, "", "visibility-notify" },
        { GDK_NO_EXPOSE, "", "no-expose" },
        { GDK_SCROLL, "", "scroll" },
        { GDK_WINDOW_STATE, "", "window-state" },
        { GDK_SETTING, "", "setting" },
        { 0, NULL, NULL }
      };*/
      etype = g_enum_register_static ("GdkEventType", NULL);//values);
    }
  return etype;
}


GType
gdk_event_mask_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
     /* static const GFlagsValue values[] = {
        { GDK_EXPOSURE_MASK, "", "exposure-mask" },
        { GDK_POINTER_MOTION_MASK, "", "pointer-motion-mask" },
        { GDK_POINTER_MOTION_HINT_MASK, "", "pointer-motion-hint-mask" },
        { GDK_BUTTON_MOTION_MASK, "", "button-motion-mask" },
        { GDK_BUTTON1_MOTION_MASK, "", "button1-motion-mask" },
        { GDK_BUTTON2_MOTION_MASK, "", "button2-motion-mask" },
        { GDK_BUTTON3_MOTION_MASK, "", "button3-motion-mask" },
        { GDK_BUTTON_PRESS_MASK, "", "button-press-mask" },
        { GDK_BUTTON_RELEASE_MASK, "", "button-release-mask" },
        { GDK_KEY_PRESS_MASK, "", "key-press-mask" },
        { GDK_KEY_RELEASE_MASK, "", "key-release-mask" },
        { GDK_ENTER_NOTIFY_MASK, "", "enter-notify-mask" },
        { GDK_LEAVE_NOTIFY_MASK, "", "leave-notify-mask" },
        { GDK_FOCUS_CHANGE_MASK, "", "focus-change-mask" },
        { GDK_STRUCTURE_MASK, "", "structure-mask" },
        { GDK_PROPERTY_CHANGE_MASK, "", "property-change-mask" },
        { GDK_VISIBILITY_NOTIFY_MASK, "", "visibility-notify-mask" },
        { GDK_PROXIMITY_IN_MASK, "", "proximity-in-mask" },
        { GDK_PROXIMITY_OUT_MASK, "", "proximity-out-mask" },
        { GDK_SUBSTRUCTURE_MASK, "", "substructure-mask" },
        { GDK_SCROLL_MASK, "", "scroll-mask" },
        { GDK_ALL_EVENTS_MASK, "", "all-events-mask" },
        { 0, NULL, NULL }
      };*/
      etype = g_flags_register_static ("GdkEventMask", NULL);// values);
    }
  return etype;
}


GType
gdk_visibility_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_VISIBILITY_UNOBSCURED, "", "unobscured" },
        { GDK_VISIBILITY_PARTIAL, "", "partial" },
        { GDK_VISIBILITY_FULLY_OBSCURED, "", "fully-obscured" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkVisibilityState", values);
    }
  return etype;
}


GType
gdk_scroll_direction_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_SCROLL_UP, "", "up" },
        { GDK_SCROLL_DOWN, "", "down" },
        { GDK_SCROLL_LEFT, "", "left" },
        { GDK_SCROLL_RIGHT, "", "right" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkScrollDirection", values);
    }
  return etype;
}


GType
gdk_notify_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_NOTIFY_ANCESTOR, "", "ancestor" },
        { GDK_NOTIFY_VIRTUAL, "", "virtual" },
        { GDK_NOTIFY_INFERIOR, "", "inferior" },
        { GDK_NOTIFY_NONLINEAR, "", "nonlinear" },
        { GDK_NOTIFY_NONLINEAR_VIRTUAL, "", "nonlinear-virtual" },
        { GDK_NOTIFY_UNKNOWN, "", "unknown" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkNotifyType", values);
    }
  return etype;
}


GType
gdk_crossing_mode_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_CROSSING_NORMAL, "", "normal" },
        { GDK_CROSSING_GRAB, "", "grab" },
        { GDK_CROSSING_UNGRAB, "", "ungrab" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkCrossingMode", values);
    }
  return etype;
}


GType
gdk_property_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_PROPERTY_NEW_VALUE, "", "new-value" },
        { GDK_PROPERTY_DELETE, "", "delete" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkPropertyState", values);
    }
  return etype;
}


GType
gdk_window_state_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_WINDOW_STATE_WITHDRAWN, "", "withdrawn" },
        { GDK_WINDOW_STATE_ICONIFIED, "", "iconified" },
        { GDK_WINDOW_STATE_MAXIMIZED, "", "maximized" },
        { GDK_WINDOW_STATE_STICKY, "", "sticky" },
        { GDK_WINDOW_STATE_FULLSCREEN, "", "fullscreen" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkWindowState", values);
    }
  return etype;
}


GType
gdk_setting_action_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_SETTING_ACTION_NEW, "", "new" },
        { GDK_SETTING_ACTION_CHANGED, "", "changed" },
        { GDK_SETTING_ACTION_DELETED, "", "deleted" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkSettingAction", values);
    }
  return etype;
}


GType
gdk_font_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_FONT_FONT, "", "font" },
        { GDK_FONT_FONTSET, "", "fontset" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkFontType", values);
    }
  return etype;
}


GType
gdk_cap_style_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_CAP_NOT_LAST, "", "not-last" },
        { GDK_CAP_BUTT, "", "butt" },
        { GDK_CAP_ROUND, "", "round" },
        { GDK_CAP_PROJECTING, "", "projecting" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkCapStyle", values);
    }
  return etype;
}


GType
gdk_fill_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_SOLID, "", "solid" },
        { GDK_TILED, "", "tiled" },
        { GDK_STIPPLED, "", "stippled" },
        { GDK_OPAQUE_STIPPLED, "", "opaque-stippled" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkFill", values);
    }
  return etype;
}


GType
gdk_function_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
/*      static const GEnumValue values[] = {
        { GDK_COPY, "", "copy" },
        { GDK_INVERT, "", "invert" },
        { GDK_XOR, "", "xor" },
        { GDK_CLEAR, "", "clear" },
        { GDK_AND, "", "and" },
        { GDK_AND_REVERSE, "", "and-reverse" },
        { GDK_AND_INVERT, "", "and-invert" },
        { GDK_NOOP, "", "noop" },
        { GDK_OR, "", "or" },
        { GDK_EQUIV, "", "equiv" },
        { GDK_OR_REVERSE, "", "or-reverse" },
        { GDK_COPY_INVERT, "", "copy-invert" },
        { GDK_OR_INVERT, "", "or-invert" },
        { GDK_NAND, "", "nand" },
        { GDK_NOR, "", "nor" },
        { GDK_SET, "", "set" },
        { 0, NULL, NULL }
      };*/
      etype = g_enum_register_static ("GdkFunction", NULL);//values);
    }
  return etype;
}


GType
gdk_join_style_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_JOIN_MITER, "", "miter" },
        { GDK_JOIN_ROUND, "", "round" },
        { GDK_JOIN_BEVEL, "", "bevel" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkJoinStyle", values);
    }
  return etype;
}


GType
gdk_line_style_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_LINE_SOLID, "", "solid" },
        { GDK_LINE_ON_OFF_DASH, "", "on-off-dash" },
        { GDK_LINE_DOUBLE_DASH, "", "double-dash" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkLineStyle", values);
    }
  return etype;
}


GType
gdk_subwindow_mode_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_CLIP_BY_CHILDREN, "", "clip-by-children" },
        { GDK_INCLUDE_INFERIORS, "", "include-inferiors" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkSubwindowMode", values);
    }
  return etype;
}


GType
gdk_gc_values_mask_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
     /* static const GFlagsValue values[] = {
        { GDK_GC_FOREGROUND, "", "foreground" },
        { GDK_GC_BACKGROUND, "", "background" },
        { GDK_GC_FONT, "", "font" },
        { GDK_GC_FUNCTION, "", "function" },
        { GDK_GC_FILL, "", "fill" },
        { GDK_GC_TILE, "", "tile" },
        { GDK_GC_STIPPLE, "", "stipple" },
        { GDK_GC_CLIP_MASK, "", "clip-mask" },
        { GDK_GC_SUBWINDOW, "", "subwindow" },
        { GDK_GC_TS_X_ORIGIN, "", "ts-x-origin" },
        { GDK_GC_TS_Y_ORIGIN, "", "ts-y-origin" },
        { GDK_GC_CLIP_X_ORIGIN, "", "clip-x-origin" },
        { GDK_GC_CLIP_Y_ORIGIN, "", "clip-y-origin" },
        { GDK_GC_EXPOSURES, "", "exposures" },
        { GDK_GC_LINE_WIDTH, "", "line-width" },
        { GDK_GC_LINE_STYLE, "", "line-style" },
        { GDK_GC_CAP_STYLE, "", "cap-style" },
        { GDK_GC_JOIN_STYLE, "", "join-style" },
        { 0, NULL, NULL }
      };*/
      etype = g_flags_register_static ("GdkGCValuesMask", NULL); //values);
    }
  return etype;
}


GType
gdk_image_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
    /*  static const GEnumValue values[] = {
        { GDK_IMAGE_NORMAL, "", "normal" },
        { GDK_IMAGE_SHARED, "", "shared" },
        { GDK_IMAGE_FASTEST, "", "fastest" },
        { 0, NULL, NULL }
      };*/
      etype = g_enum_register_static ("GdkImageType", NULL);//values);
    }
  return etype;
}


GType
gdk_extension_mode_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_EXTENSION_EVENTS_NONE, "", "none" },
        { GDK_EXTENSION_EVENTS_ALL, "", "all" },
        { GDK_EXTENSION_EVENTS_CURSOR, "", "cursor" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkExtensionMode", values);
    }
  return etype;
}


GType
gdk_input_source_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_SOURCE_MOUSE, "", "mouse" },
        { GDK_SOURCE_PEN, "", "pen" },
        { GDK_SOURCE_ERASER, "", "eraser" },
        { GDK_SOURCE_CURSOR, "", "cursor" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkInputSource", values);
    }
  return etype;
}


GType
gdk_input_mode_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_MODE_DISABLED, "", "disabled" },
        { GDK_MODE_SCREEN, "", "screen" },
        { GDK_MODE_WINDOW, "", "window" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkInputMode", values);
    }
  return etype;
}


GType
gdk_axis_use_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_AXIS_IGNORE, "", "ignore" },
        { GDK_AXIS_X, "", "x" },
        { GDK_AXIS_Y, "", "y" },
        { GDK_AXIS_PRESSURE, "", "pressure" },
        { GDK_AXIS_XTILT, "", "xtilt" },
        { GDK_AXIS_YTILT, "", "ytilt" },
        { GDK_AXIS_WHEEL, "", "wheel" },
        { GDK_AXIS_LAST, "", "last" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkAxisUse", values);
    }
  return etype;
}


GType
gdk_prop_mode_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_PROP_MODE_REPLACE, "", "replace" },
        { GDK_PROP_MODE_PREPEND, "", "prepend" },
        { GDK_PROP_MODE_APPEND, "", "append" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkPropMode", values);
    }
  return etype;
}


GType
gdk_fill_rule_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_EVEN_ODD_RULE, "", "even-odd-rule" },
        { GDK_WINDING_RULE, "", "winding-rule" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkFillRule", values);
    }
  return etype;
}


GType
gdk_overlap_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_OVERLAP_RECTANGLE_IN, "", "in" },
        { GDK_OVERLAP_RECTANGLE_OUT, "", "out" },
        { GDK_OVERLAP_RECTANGLE_PART, "", "part" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkOverlapType", values);
    }
  return etype;
}


GType
gdk_rgb_dither_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_RGB_DITHER_NONE, "", "none" },
        { GDK_RGB_DITHER_NORMAL, "", "normal" },
        { GDK_RGB_DITHER_MAX, "", "max" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkRgbDither", values);
    }
  return etype;
}


GType
gdk_byte_order_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_LSB_FIRST, "", "lsb-first" },
        { GDK_MSB_FIRST, "", "msb-first" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkByteOrder", values);
    }
  return etype;
}


GType
gdk_modifier_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_SHIFT_MASK, "", "shift-mask" },
        { GDK_LOCK_MASK, "", "lock-mask" },
        { GDK_CONTROL_MASK, "", "control-mask" },
        { GDK_MOD1_MASK, "", "mod1-mask" },
        { GDK_MOD2_MASK, "", "mod2-mask" },
        { GDK_MOD3_MASK, "", "mod3-mask" },
        { GDK_MOD4_MASK, "", "mod4-mask" },
        { GDK_MOD5_MASK, "", "mod5-mask" },
        { GDK_BUTTON1_MASK, "", "button1-mask" },
        { GDK_BUTTON2_MASK, "", "button2-mask" },
        { GDK_BUTTON3_MASK, "", "button3-mask" },
        { GDK_BUTTON4_MASK, "", "button4-mask" },
        { GDK_BUTTON5_MASK, "", "button5-mask" },
        { GDK_RELEASE_MASK, "", "release-mask" },
        { GDK_MODIFIER_MASK, "", "modifier-mask" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkModifierType", values);
    }
  return etype;
}


GType
gdk_input_condition_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
  /*    static const GFlagsValue values[] = {
        { GDK_INPUT_READ, "", "read" },
        { GDK_INPUT_WRITE, "", "write" },
        { GDK_INPUT_EXCEPTION, "", "exception" },
        { 0, NULL, NULL }
      };*/
      etype = g_flags_register_static ("GdkInputCondition", NULL);//values);
    }
  return etype;
}


GType
gdk_status_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_OK, "", "ok" },
        { GDK_ERROR, "", "error" },
        { GDK_ERROR_PARAM, "", "error-param" },
        { GDK_ERROR_FILE, "", "error-file" },
        { GDK_ERROR_MEM, "", "error-mem" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkStatus", values);
    }
  return etype;
}


GType
gdk_grab_status_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_GRAB_SUCCESS, "", "success" },
        { GDK_GRAB_ALREADY_GRABBED, "", "already-grabbed" },
        { GDK_GRAB_INVALID_TIME, "", "invalid-time" },
        { GDK_GRAB_NOT_VIEWABLE, "", "not-viewable" },
        { GDK_GRAB_FROZEN, "", "frozen" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkGrabStatus", values);
    }
  return etype;
}


GType
gdk_visual_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_VISUAL_STATIC_GRAY, "", "static-gray" },
        { GDK_VISUAL_GRAYSCALE, "", "grayscale" },
        { GDK_VISUAL_STATIC_COLOR, "", "static-color" },
        { GDK_VISUAL_PSEUDO_COLOR, "", "pseudo-color" },
        { GDK_VISUAL_TRUE_COLOR, "", "true-color" },
        { GDK_VISUAL_DIRECT_COLOR, "", "direct-color" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkVisualType", values);
    }
  return etype;
}


GType
gdk_window_class_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_INPUT_OUTPUT, "", "output" },
        { GDK_INPUT_ONLY, "", "only" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkWindowClass", values);
    }
  return etype;
}


GType
gdk_window_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_WINDOW_ROOT, "", "root" },
        { GDK_WINDOW_TOPLEVEL, "", "toplevel" },
        { GDK_WINDOW_CHILD, "", "child" },
        { GDK_WINDOW_DIALOG, "", "dialog" },
        { GDK_WINDOW_TEMP, "", "temp" },
        { GDK_WINDOW_FOREIGN, "", "foreign" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkWindowType", values);
    }
  return etype;
}


GType
gdk_window_attributes_type_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_WA_TITLE, "", "title" },
        { GDK_WA_X, "", "x" },
        { GDK_WA_Y, "", "y" },
        { GDK_WA_CURSOR, "", "cursor" },
        { GDK_WA_COLORMAP, "", "colormap" },
        { GDK_WA_VISUAL, "", "visual" },
        { GDK_WA_WMCLASS, "", "wmclass" },
        { GDK_WA_NOREDIR, "", "noredir" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkWindowAttributesType", values);
    }
  return etype;
}


GType
gdk_window_hints_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_HINT_POS, "", "pos" },
        { GDK_HINT_MIN_SIZE, "", "min-size" },
        { GDK_HINT_MAX_SIZE, "", "max-size" },
        { GDK_HINT_BASE_SIZE, "", "base-size" },
        { GDK_HINT_ASPECT, "", "aspect" },
        { GDK_HINT_RESIZE_INC, "", "resize-inc" },
        { GDK_HINT_WIN_GRAVITY, "", "win-gravity" },
        { GDK_HINT_USER_POS, "", "user-pos" },
        { GDK_HINT_USER_SIZE, "", "user-size" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkWindowHints", values);
    }
  return etype;
}


GType
gdk_window_type_hint_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_WINDOW_TYPE_HINT_NORMAL, "", "normal" },
        { GDK_WINDOW_TYPE_HINT_DIALOG, "", "dialog" },
        { GDK_WINDOW_TYPE_HINT_MENU, "", "menu" },
        { GDK_WINDOW_TYPE_HINT_TOOLBAR, "", "toolbar" },
        { GDK_WINDOW_TYPE_HINT_SPLASHSCREEN, "", "splashscreen" },
        { GDK_WINDOW_TYPE_HINT_UTILITY, "", "utility" },
        { GDK_WINDOW_TYPE_HINT_DOCK, "", "dock" },
        { GDK_WINDOW_TYPE_HINT_DESKTOP, "", "desktop" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkWindowTypeHint", values);
    }
  return etype;
}


GType
gdk_wm_decoration_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_DECOR_ALL, "", "all" },
        { GDK_DECOR_BORDER, "", "border" },
        { GDK_DECOR_RESIZEH, "", "resizeh" },
        { GDK_DECOR_TITLE, "", "title" },
        { GDK_DECOR_MENU, "", "menu" },
        { GDK_DECOR_MINIMIZE, "", "minimize" },
        { GDK_DECOR_MAXIMIZE, "", "maximize" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkWMDecoration", values);
    }
  return etype;
}


GType
gdk_wm_function_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GFlagsValue values[] = {
        { GDK_FUNC_ALL, "", "all" },
        { GDK_FUNC_RESIZE, "", "resize" },
        { GDK_FUNC_MOVE, "", "move" },
        { GDK_FUNC_MINIMIZE, "", "minimize" },
        { GDK_FUNC_MAXIMIZE, "", "maximize" },
        { GDK_FUNC_CLOSE, "", "close" },
        { 0, NULL, NULL }
      };
      etype = g_flags_register_static ("GdkWMFunction", values);
    }
  return etype;
}


GType
gdk_gravity_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_GRAVITY_NORTH_WEST, "", "north-west" },
        { GDK_GRAVITY_NORTH, "", "north" },
        { GDK_GRAVITY_NORTH_EAST, "", "north-east" },
        { GDK_GRAVITY_WEST, "", "west" },
        { GDK_GRAVITY_CENTER, "", "center" },
        { GDK_GRAVITY_EAST, "", "east" },
        { GDK_GRAVITY_SOUTH_WEST, "", "south-west" },
        { GDK_GRAVITY_SOUTH, "", "south" },
        { GDK_GRAVITY_SOUTH_EAST, "", "south-east" },
        { GDK_GRAVITY_STATIC, "", "static" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkGravity", values);
    }
  return etype;
}


GType
gdk_window_edge_get_type (void)
{
  static GType etype = 0;
  if (etype == 0)
    {
      static const GEnumValue values[] = {
        { GDK_WINDOW_EDGE_NORTH_WEST, "", "north-west" },
        { GDK_WINDOW_EDGE_NORTH, "", "north" },
        { GDK_WINDOW_EDGE_NORTH_EAST, "", "north-east" },
        { GDK_WINDOW_EDGE_WEST, "", "west" },
        { GDK_WINDOW_EDGE_EAST, "", "east" },
        { GDK_WINDOW_EDGE_SOUTH_WEST, "", "south-west" },
        { GDK_WINDOW_EDGE_SOUTH, "", "south" },
        { GDK_WINDOW_EDGE_SOUTH_EAST, "", "south-east" },
        { 0, NULL, NULL }
      };
      etype = g_enum_register_static ("GdkWindowEdge", values);
    }
  return etype;
}

